@startuml
    title conan learning usecases

    actor "Developer 1" as Dev1
    actor "Developer 2" as Dev2
    actor "Developer 3" as Dev3
    actor "Developer 4" as Dev4

    package conan_gtest {
        usecase "build custom package" as Build
        usecase "run unit tests" as Test
        usecase "create new package" as Package
    }

    package conan_gtest_use {
        usecase "include package" as Include
    }

    package nonconan {
        usecase "adapt to conan package" as Adapt
    }

    package crossbuild {
        usecase "perform crossbuild" as Crossbuild
    }

    Dev1 --> Build
    Dev1 --> Test
    Dev1 --> Package

    Dev2 --> Include

    Dev3 --> Adapt

    Dev4 --> Crossbuild

' hidden connector gymnastics for proper layout of components
    Test -[hidden]-> Dev2
    Include -[hidden]-> Dev3
    Adapt -[hidden]-> Dev4
@enduml